spring:
  datasource:
    url: jdbc:h2:file:./data/springBatchDemo
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  batch:
    initialize-schema: always